module.exports = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'consistent',
  jsxSingleQuote: true,
  trailingComma: 'none',
  bracketSpacing: true,
  bracketSameLine: true,
  arrowParens: 'always',
  rangeStart: 0,
  rangeEnd: Infinity,
  endOfLine: 'auto',
  singleAttributePerLine: false,
  plugins: [],
  overrides: [],
};
